# Generated by Django 4.1.7 on 2023-03-02 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_company_job_matrimony_event_photos_drive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='related_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='related_matrimony',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.matrimony'),
        ),
    ]
